version: '3.7'
services:
  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    container_name: composer01
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - composer
    container_name: php01
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx01
    depends_on:
      - php
    ports:
      - 80:80
      - 4200:4200
